### ISSUE TITLE
jimbauserman's comments on First Big Idea

### ISSUE THREAD

**Issue by jimbauserman** [w201rdada/portfolio-Siilbon#3]
Summary:
Dynamically "score" alarms from manufacturing equipment to prioritize responses to these alarms and reduce false alarms (literally) from distracting operators.

Keep:
Robust discussion of potential outcomes from a properly managed alarm system. There are quite a few different avenues through which this system could improve productivity and you explore them well.

Cut:
Some of the speculation as to how to conquer hurdles. This seems more appropriate to discuss while actually implementing the system, rather than just while pitching it.

Rearrange:
I think the middle paragraphs of the middle section more properly belong in the end, as they seem to be more about the consequences of the system working well than how it will work per se. Much of this discussion could be reframed in terms of features of the algorithm and the feedback it would output, which could be left in the middle section, and then the actions taken based on these outputs could be moved to the end. 

Add:
More discussion of what actual features are available for each alarm. I can surmise that you would know at least which machine is generating an alarm, which operator is on staff, and what the consequences of the alarm are. Would you also know what circumstances cause the alarm to trigger? Could these triggers be adjusted based on output from the algorithm? Do alarms vary in how easy they are to diagnose?

**Comment by Siilbon** [comment]
I tried to add a little more background about the existing system to help contextualize my idea.  I also added an example to the middle which describes one scenario where the model discerns between low and high priority problems triggered by the same type of alarm signal.  I like your suggestion about dynamic alarm limits, I decided not to include a discussion about them because topic is already very broad with what I chose to focus on.
